### ISSUE TITLE
Retention time in the HTML page

### ISSUE THREAD

**Issue by jlausuch** [grisu48/pasta#38]
In the HTML page, I would like to have the option to define the expiration date (simple text box with some minimal date validation is enough) with the possibility to select "never".

Or maybe, a select box with some options. For instance:
- 1 day
- 1 week
- 1 moth
- 2 months
- 6 months
- 1 year
- never

**Comment by grisu48** [comment]
Good idea! Will do whenever I have some time

**Comment by grisu48** [comment]
Moved to https://codeberg.org/grisu48/pasta/issues/3
