### ISSUE TITLE
Feature request: listing existing pastas

### ISSUE THREAD

**Issue by bjornaugestad** [grisu48/pasta#46]
pasta looks great and is almost just what I've been looking for for a while. But I don't think we can expect users to remember or keep track of the Path part, so a list of pastas would be great to have. For our org, it's a must. Have you considered such a feature?

**Comment by grisu48** [comment]
Hello! If you are using the `pasta` CLI program, then it will remember and keep a list of previous uploads:

```
$ pasta ls
Id   Filename                         Date                  URL
0    IMG_20210922_085035.jpg          2021-09-22 13:01:15   http://pasta.local/AhB3BbiO
1    virt-restart                     2021-09-28 14:15:53   http://pasta.local/0wNCsNan
2    ruleset.txt                      2021-10-11 16:22:23   http://pasta.local/Rs8xdwJl
3    <none>                           1970-01-01 01:00:00   https://pasta.feldspaten.org/vv1qEWae
4    virt-host.tar.gz                 2021-10-28 15:15:53   http://pasta.local/QQuCcmaD
5    gitconfig                        2021-10-29 10:32:42   http://pasta.local/jwTC0mKD
6    pasta                            2021-11-12 09:13:39   https://pasta.feldspaten.org/aCUkSwS0
7    virt-restart                     2021-12-06 17:10:15   http://pasta.local/tvbYMgqA
```

Keeping a list of pastas on the server side would conflict with the simplicity philosophy, that's why this is not implemented there as well.

**Comment by bjornaugestad** [comment]
Hello, and thanks for the quick response :)

My use case is something like this: "Hey, I pasted the file you were
looking for. You can find it at our pastebin server."
Such a use case seems to be impossible, one has to share the URL to the
pasta manually. That makes the whole process more cumbersome.

Thanks once again for your response, and good luck with your project.

**Comment by grisu48** [comment]
I see, so it's a feature request for a listing of public pastes, did I understand this correctly?

Let me think about this for a bit, but at first I don't see any conflicting points with the main idea of the project :thinking: I want to cook the idea for a bit though first.

**Comment by bjornaugestad** [comment]
> I see, so it's a feature request for a listing of public pastes, did I understand this correctly?

Yes, correctly understood. I plan to set up your pastebin server at a company to be used by developers who aren't that experienced in using pastebins. Most don't even know what a pastebin is, so the usage threshold should be low.

**Comment by grisu48** [comment]
https://github.com/grisu48/pasta/pull/47 as a first draft, will continue to work on this probably during the weekend.

**Comment by grisu48** [comment]
I merged https://github.com/grisu48/pasta/pull/47 and created a new release for this feature.

You can use it by setting the environment variable `PASTA_PUBLICPASTAS` or setting `PublicPastas` in the [pastad.toml](https://github.com/grisu48/pasta/blob/main/pastad.toml.example) file to a value greater than zero.

Leaving the issue open for a little bit for feedback before closing. Please let me know if there are any issues with this one! Enjoy :slightly_smiling_face:
