### ISSUE TITLE
Can pasta return something else than localhost when it prints the URL?

### ISSUE THREAD

**Issue by bjornaugestad** [grisu48/pasta#48]
Title says most. Here's some extra info:

Background/setup:
1. I run pastad as a service on a Linux VM.
2. That VM is connected to "the world" via a Cloudflare tunnel and a DNS entry at Cloudflare pointing to that tunnel. The tunnel forwards traffic to the VM. 
3. The readers of pastes therefore reads by accessing the URL where hostname equals the DNS entry. 

Whenever I use pasta to send something to the pastebin server, pasta prints an url using localhost as hostname. In order to share the url, I must change the hostname to its publicly known name.

Could this be changed somehow so that pasta prints the external name? Perhaps pastad.conf could have a new attribute, "official hostname" or something similar, and return that name to pasta?

**Comment by grisu48** [comment]
Hey there.

Yes, it should - you can either pass the `PASTA_BASEURL` environment variable and set it to the hostname (e.g. `PASTA_BASEURL=https://my-awesome.pasta`) or you can configure this in the `pastad.toml` file checkout the [provided example](https://github.com/grisu48/pasta/blob/main/pastad.toml.example).

When running from a container (either docker or podman), see the https://github.com/grisu48/pasta#build-docker-image section - the `pastad.toml` file should be in the data directory.

I think this is what you are searching for?

**Comment by bjornaugestad** [comment]
Hi. 

I noticed that PASTA_BASEURL existed and considered using it too. The thing is that the network setup we're using is a bit special. The pastebin server runs on a VM inside a massive "firewall" (Cloudflare/AppGate) with one name for the server. On the other side of the "firewall", the server has another name and all access to that server is controlled by the FW. 

What I want to do, is to run the pasta command and have it return the server's external name. The tricky part is that the external name is not accessible from inside the FW. My idea was to use PASTA_BASEURL to name the server's internal name, and 'something else' for the external name. No worries though, I can probably fix this myself and perhaps provide a PR with the changes. 

Thanks again for your quick replies, and best of luck with your project!

**Comment by grisu48** [comment]
Hmm, we could introduce host variables, e.g. `$hostname` that are replaced at startup times. Then you could use something like `PASTA_BASEURL = https://$hostname`. I never though this is necessary but am not against introducing this logic. If needed I would see it as a nice addition, that goes also with the project philosophy.

Would that resolve your issue?

**Comment by grisu48** [comment]
This issue is solved with https://github.com/grisu48/pasta/pull/52 and documented in https://github.com/grisu48/pasta#macros.

Closing issue but feel free to reopen it, if you consider it not yet done.
